# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileBlog' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobileBlog
  pod "IQKeyboardManager" 

  target 'MobileBlogTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MobileBlog-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobileBlog-tvOS

  target 'MobileBlog-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
